# Site settings
title: Reach for the Stars
email: rleeman3@gmail.com
header-img: img/3bffs.jpg
description: > # this means to ignore newlines until "baseurl:"
  Read about all my crazy adventures. Get to know me!
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_username: bexster911
twitter_username: rleeman3
github_username:  rleeman3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

port: 1818